image: alpine/edge
packages: [ zola ]
oauth: pages.sr.ht/PAGES:RW
environment:
  site: www.example.org # TODO
sources:
  - https://git.sr.ht/~magno/magno-blog
tasks:
  - build: |
      cd magno-blog
      zola build
  - package: |
      cd magno-blog
      tar -C public -cvz . > ../site.tar.gz
  - upload: |
      acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
