base_url = "https://example.com"

title = "Magno Blog"
description = "My notes and other stuff about my programming projects"
default_language = "en" # "es"

# theme = ""
# output_dir = "public"

compile_sass = false
build_search_index = false
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
author = "Magno El Magnífico"
about = """Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Enim ut tellus elementum sagittis
vitae et leo duis. Odio tempor orci dapibus ultrices in iaculis. Massa massa
ultricies mi quis hendrerit dolor. Cursus euismod quis viverra nibh cras pulvinar.
"""

projects = [
    ["Project test 1", "https://www.example.com", """Lorem ipsum dolor sit amet,
    consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
    dolore magna aliqua. Enim ut tellus elementum sagittis vitae et leo duis.
    Odio tempor orci dapibus ultrices in iaculis. Massa massa ultricies mi quis
    hendrerit dolor. Cursus euismod quis viverra nibh cras pulvinar."""],

    ["Project test 2", "https://www.example.com", """Lorem ipsum dolor sit amet,
    consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
    dolore magna aliqua. Enim ut tellus elementum sagittis vitae et leo duis.
    Odio tempor orci dapibus ultrices in iaculis. Massa massa ultricies mi quis
    hendrerit dolor. Cursus euismod quis viverra nibh cras pulvinar."""],

    ["Project test 3", "https://www.example.com", """Lorem ipsum dolor sit amet,
    consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
    dolore magna aliqua. Enim ut tellus elementum sagittis vitae et leo duis.
    Odio tempor orci dapibus ultrices in iaculis. Massa massa ultricies mi quis
    hendrerit dolor. Cursus euismod quis viverra nibh cras pulvinar."""],

    ["Project test 4", "https://www.example.com", """Lorem ipsum dolor sit amet,
    consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
    dolore magna aliqua. Enim ut tellus elementum sagittis vitae et leo duis.
    Odio tempor orci dapibus ultrices in iaculis. Massa massa ultricies mi quis
    hendrerit dolor. Cursus euismod quis viverra nibh cras pulvinar."""],
]
