baseURL = "https://magnoblog.netlify.app"
languageCode = "es"
title = "Magno Blog"
enableEmoji = true

[author]
# Footer and about (home.html)
name = "Magno El Magnífico"

[params]
# Blog logo (start:home.html), header, and icon on the tab
logo = "/logo.svg"

# When true, shows posts' weight on `page-entry.html` (easier for sorting)
debug = false

[markup.highlight]
# https://xyproto.github.io/splash/docs/all.html
# "dracula", "fruity", "paraiso-dark", "rrt", "solarized-dark256", "vim"
style = "dracula"

tabWidth = 4
# Create links for each line of code
anchorLineNos = true
guessSyntax = true

lineNos = true
lineNumbersInTable = false

[markup.tableOfContents]
startLevel = 0
endLevel = 100
ordered = true
