baseURL = "https://magnoblog.netlify.app"
languageCode = "es"
title = "Magno Blog"
enableEmoji = true

[params]
# Footer and about (home.html)
author.name = "Magno El Magnífico"

# Blog logo (start:home.html), header, and icon on the tab
logo = "/logo.svg"

[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files

[markup.highlight]
# https://xyproto.github.io/splash/docs/all.html
# "dracula", "fruity", "paraiso-dark", "rrt", "solarized-dark256", "vim"
style = "dracula"

tabWidth = 4
anchorLineNos = true # Create links for each line of code
guessSyntax = true

lineNos = true
lineNumbersInTable = false

[markup.tableOfContents]
startLevel = 0
endLevel = 100
ordered = true
